Algoritmo "looping2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/03/2023
Var
 i,n,x: inteiro



Inicio
     i:=1
     escreva("digite um número: ")
     leia(n)
     para i de 1 ate 10 passo 1 faca
      x:=n*i
      i:=i+1
      escreva(x)
     fimpara
Fimalgoritmo